// All primary redirects ([source, destination, permanent? (default true)])

/** @type { [string, string, boolean | undefined][] } */
module.exports = [
  ["/developers/docs/evm", "/developers/docs/qvm/"],
  ["/developers/docs/evm/opcodes", "/developers/docs/qvm/opcodes/"],
  ["/discord", "https://discord.gg/MSctkBT5j"],
  ["/brand", "/assets/"],
  ["/what-is-ethereum", "/what-is-quantaureum/"],
  ["/what-is-ether", "/what-is-qau/"],
  ["/ether", "/what-is-qau/"],
  ["/eth", "/what-is-qau/"],
  ["/token", "/developers/"],
  ["/cli", "/developers/"],
  ["/roadmap/vision", "/roadmap/"],
  ["/roadmap/future-proofing", "/roadmap/security/"],
  [
    "/roadmap/future-proofing/quantum-resistance",
    "/roadmap/security/quantum-resistance/",
  ],
  ["/search", "/"],
  ["/download", "/wallets/find-wallet/"],
  ["/how", "/guides/"],
  ["/nfts", "/nft/"],
  ["/daos", "/dao/"],
  ["/layer2", "/layer-2/"],
  ["/grants", "/community/grants/"],
  ["/java", "/developers/docs/programming-languages/java/"],
  ["/python", "/developers/docs/programming-languages/python/"],
  ["/javascript", "/developers/docs/programming-languages/javascript/"],
  ["/golang", "/developers/docs/programming-languages/golang/"],
  ["/rust", "/developers/docs/programming-languages/rust/"],
  ["/dot-net", "/developers/docs/programming-languages/dot-net/"],
  ["/delphi", "/developers/docs/programming-languages/delphi/"],
  ["/dart", "/developers/docs/programming-languages/dart/"],
  ["/beginners", "/what-is-quantaureum/"],
  ["/build", "/developers/tools/"],

  // Former ethereum.org eth2/roadmap/upgrade URLs now point at the generic
  // Quantaureum roadmap and staking hubs. Historical sub-paths were removed.
  ["/eth2", "/roadmap/"],
  ["/eth2/:path*", "/roadmap/"],
  ["/upgrades", "/roadmap/"],
  ["/upgrades/:path*", "/roadmap/"],
  ["/garden", "/roadmap/"],

  ["/deprecated-software", "/apps/"],
  ["/dashboards", "/resources"],
  ["/history", "/roadmap/"],
  ["/wallet", "/wallets/"],
  ["/beginners", "/what-is-quantaureum/"],

  // Developer docs legacy paths (generic, chain-agnostic)
  [
    "/developers/learning-tools",
    "/developers/tools/categories/education-standards/",
  ],
  ["/developers/local-environment", "/developers/tools/"],
  ["/developers/docs/scaling/layer-2-rollups", "/developers/docs/scaling"],
  ["/developers/docs/layer-2-scaling", "/layer-2/"],
  ["/developers/docs/zk", "/zero-knowledge-proofs/"],
  ["/developers/docs/zk-snarks", "/zero-knowledge-proofs/"],
  ["/developers/docs/security", "/developers/docs/smart-contracts/security/"],
  ["/developers/docs/wallets", "/wallets/"],
  ["/developers/docs/daos", "/dao/"],
  ["/developers/docs/rollups", "/developers/docs/scaling/#rollups"],
  [
    "/developers/docs/smart-contracts/source-code-verification",
    "/developers/docs/smart-contracts/verifying/",
  ],
  [
    "/developers/docs/smart-contracts/upgrading-smart-contracts",
    "/developers/docs/smart-contracts/upgrading/",
  ],
  [
    "/developers/docs/consensus-mechanisms/proof-of-stake",
    "/developers/docs/consensus-mechanisms/pos/",
  ],
  [
    "/developers/docs/consensus-mechanisms/pos/slashing",
    "/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/",
  ],
  ["/developers/docs/ides/%23web-based-ides", "/developers/docs/"],
  ["/developers/docs/scaling/rollups", "/developers/docs/scaling/#rollups"],
  [
    "/developers/docs/scaling/layer-2",
    "/developers/docs/scaling/#layer-2-scaling",
  ],

  // Removed legacy ethereum.org hub pages — point at the closest Quantaureum equivalent
  ["/enterprise", "/about/"],
  ["/enterprise/:path*", "/about/"],
  ["/use", "/apps/"],
  ["/dapps", "/apps/"],
  ["/team", "/about/"],
  ["/donate", "/"],
  ["/blog", "/"],
  ["/tds", "/"],
  ["/trillion-dollar-security", "/"],
  ["/10-years", "/"],
  ["/10years", "/"],
  ["/about/:path*", "/about/"],
  [
    "/guides/how-to-register-an-ethereum-account",
    "/guides/how-to-create-an-account/",
  ],
  [
    "/guides/how-to-create-an-ethereum-account",
    "/guides/how-to-create-an-account/",
  ],
  ["/wlan", "/wallets/find-wallet/"],
  ["/wallets/security", "/security/"],
  ["/zero-knowledge", "/zero-knowledge-proofs/"],
  ["/layer-2-scaling", "/layer-2/"],
  ["/layer-2-scaling/rollups", "/developers/docs/scaling/"],
  ["/layer-1-scaling/sidechains", "/developers/docs/scaling/sidechains/"],
  [
    "/layer-2-scaling/state-channels",
    "/developers/docs/scaling/state-channels/",
  ],
  ["/staking/withdraws", "/staking/withdrawals/"],
  ["/languages", "/community/language-resources/"],

  // Pages removed from the QAU site: send old URLs to the closest live hub.
  ["/apps", "/explorer/"],
  ["/developers/docs", "/developers/#docs"],
  ["/developers/docs/qvm", "/developers/#docs"],
  ["/developers/docs/consensus-mechanisms", "/developers/#docs"],
  ["/developers/docs/nodes-and-clients", "/run-a-node/"],
  ["/developers/docs/nodes-and-clients/run-a-node", "/run-a-node/"],
  ["/developers/docs/nodes-and-clients/client-diversity", "/run-a-node/"],
  ["/roadmap/security", "/roadmap/#technical-upgrades"],
  ["/roadmap/security/quantum-resistance", "/roadmap/#technical-upgrades"],
  ["/roadmap/scaling", "/roadmap/#technical-upgrades"],
  ["/roadmap/privacy", "/roadmap/#technical-upgrades"],
  ["/roadmap/user-experience", "/roadmap/#changes-coming"],
  ["/roadmap/verkle-trees", "/roadmap/#technical-upgrades"],
]
